name: Deploy PHP app to Azure App Service

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on:  ubuntu-lastest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up  PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version:  "8.4"
      

      - name: Run basic PHP lint
        run:  php -l  index.php
      
      - name: Deploy  to  Azure App Service
      - uses: azure/webapps-deploy@v2
      - with:
        app-name: app-cloud-da
        publish-profile:  ${{secrets.AZURE_PUBLISH_PROFILE}}
        package:  .